### ISSUE TITLE
umd [improvment]

### ISSUE THREAD

**Issue by djleonskennedy** [hemanth/promise-to-task#1]
Please add umd version to use it in browser

**Comment by hemanth** [comment]
Did you try any web bundler?

**Comment by djleonskennedy** [comment]
Yes, i'm using webpack
- and all work well, however i use webpack plugin to clean build and it fails here :(

https://github.com/djleonskennedy/ng-annotate-cleaner/blob/master/src/ng-annotate-cleaner.js#L23

Might be i missed some thing but `compilation.assets` is `undefined`, if i remove plugin `promise-to-task` plugin works well

**Comment by hemanth** [comment]
I can UMDfiy it but these seems like an issues that must be reported in `webpack` as well.

**Comment by djleonskennedy** [comment]
ok, thank you
